FROM alpine:3.5
LABEL name="terraform"
LABEL version=0.9.2-dev
LABEL maintainer="Stephane Jourdan <fasten@fastmail.fm>"
MAINTAINER Stephane Jourdan <fasten@fastmail.fm>
ENV TERRAFORM_VERSION=0.9.2-dev
VOLUME ["/data"]
WORKDIR /data
RUN apk --update --no-cache add ca-certificates openssl sudo && rm -rf /var/cache/apk/*
COPY terraform /bin/terraform
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["--help"]
